import { Head } from "$fresh/runtime.ts";
import Footer from "../components/parts/Footer.tsx";
import Header from "../components/parts/Header.tsx";

export default function Terms() {
  return (
    <>
      <Head>
        <title>Terms of Service</title>
        <meta name="robots" content="noindex, nofollow" />
        <link
          rel="icon"
          href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>📃</text></svg>"
        />
        <link rel="canonical" href="https://myniq.app/terms" />
      </Head>
      <Header />
      <main className="bg-slate-50 pt-4 pb-24 text-slate-800">
        <div
          className="max-w-2xl mx-auto flex flex-col justify-center items-center"
        >
          <div className="flex flex-col">
            <h1 className="text-xl mb-2">Terms</h1>

            <ol type="1" className="ml-4 list-decimal">
              <caption>Terms of Service</caption>
              <li>
                Acceptance of Terms: By accessing or using our website, you
                agree to be bound by these Terms of Service. If you do not agree
                to these terms, please do not use our website.
              </li>
              <li>
                Description of Service: Our website provides daily AI-generated
                English novels and accompanying learning-focused test questions
                for educational purposes.
                <ul className="ml-4">
                  <li>
                    The English novels provided by our service are works of
                    fiction generated by artificial intelligence (AI), and they
                    bear no relation to real individuals, events, dates, or any
                    other content. The content of the novels is purely fictional
                    and unrelated to real-world occurrences or persons.
                  </li>
                  <li>
                    Additionally, the English learning test questions included
                    in our service are intended to enhance users' English
                    proficiency, but we make no guarantees regarding their
                    accuracy or effectiveness. Users are encouraged to consult
                    with experts or educators before taking action based on the
                    results of the test questions.
                  </li>
                  <li>
                    The service provider assumes no responsibility for any
                    damages or issues arising from the use of our service. Users
                    are solely responsible for their use of the service and are
                    encouraged to exercise judgment and take action as
                    necessary.
                  </li>
                </ul>
              </li>
              <li>
                User Conduct: You agree to use our website only for lawful
                purposes and in a manner that does not infringe upon the rights
                of others or inhibit their use and enjoyment of the website.
              </li>
              <li>
                Intellectual Property: All content provided on our website,
                including but not limited to text, graphics, logos, images, and
                software, is the property of our company and is protected by
                copyright and other intellectual property laws.
              </li>
              <li>
                Disclaimer of Warranties: Our website is provided on an "as is"
                and "as available" basis. We make no warranties, express or
                implied, regarding the accuracy, reliability, or availability of
                our website or its content.
              </li>
              <li>
                Limitation of Liability: In no event shall we be liable for any
                direct, indirect, incidental, special, or consequential damages
                arising out of or in any way connected with your use of our
                website.
              </li>
              <li>
                Governing Law: These Terms of Service shall be governed by and
                construed in accordance with the laws of Japan, without regard
                to its conflict of law provisions.
              </li>
              <li>
                Changes to Terms: We reserve the right to modify or replace
                these Terms of Service at any time. Your continued use of our
                website after any such changes constitutes your acceptance of
                the new Terms of Service.
              </li>
              <li>
                Contact Us: If you have any questions or concerns about these
                Terms of Service, please contact us at X or Facebook.
              </li>
            </ol>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
}
