// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $lp_forJP from "./routes/lp/forJP.tsx";
import * as $pages_date_ from "./routes/pages/[date].tsx";
import * as $report from "./routes/report.tsx";
import * as $sitemap_xml from "./routes/sitemap.xml.ts";
import * as $terms from "./routes/terms.tsx";
import * as $GtagEvent from "./islands/GtagEvent.tsx";
import * as $LazyLoadOGP from "./islands/LazyLoadOGP.tsx";
import * as $Printer from "./islands/Printer.tsx";
import * as $YoutubeAudio from "./islands/YoutubeAudio.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
    "./routes/lp/forJP.tsx": $lp_forJP,
    "./routes/pages/[date].tsx": $pages_date_,
    "./routes/report.tsx": $report,
    "./routes/sitemap.xml.ts": $sitemap_xml,
    "./routes/terms.tsx": $terms,
  },
  islands: {
    "./islands/GtagEvent.tsx": $GtagEvent,
    "./islands/LazyLoadOGP.tsx": $LazyLoadOGP,
    "./islands/Printer.tsx": $Printer,
    "./islands/YoutubeAudio.tsx": $YoutubeAudio,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
