// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_dailyQuiz from "./routes/api/dailyQuiz.ts";
import * as $index from "./routes/index.tsx";
import * as $pages_date_ from "./routes/pages/[date].tsx";
import * as $pages_report from "./routes/pages/report.tsx";
import * as $LazyLoadOGP from "./islands/LazyLoadOGP.tsx";
import * as $Printer from "./islands/Printer.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/dailyQuiz.ts": $api_dailyQuiz,
    "./routes/index.tsx": $index,
    "./routes/pages/[date].tsx": $pages_date_,
    "./routes/pages/report.tsx": $pages_report,
  },
  islands: {
    "./islands/LazyLoadOGP.tsx": $LazyLoadOGP,
    "./islands/Printer.tsx": $Printer,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
