// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $ads_txt from "./routes/ads.txt.ts";
import * as $bookshelf from "./routes/bookshelf.ts";
import * as $index from "./routes/index.tsx";
import * as $lp_forCN from "./routes/lp/forCN.tsx";
import * as $lp_forES from "./routes/lp/forES.tsx";
import * as $lp_forJP from "./routes/lp/forJP.tsx";
import * as $lp_forPT from "./routes/lp/forPT.tsx";
import * as $lp_forTW from "./routes/lp/forTW.tsx";
import * as $pages_date_ from "./routes/pages/[date].tsx";
import * as $report from "./routes/report.tsx";
import * as $robots_txt from "./routes/robots.txt.ts";
import * as $sitemap_xml from "./routes/sitemap.xml.ts";
import * as $tags_flavor_flavor_ from "./routes/tags/flavor/[flavor].tsx";
import * as $tags_flavor_theme_flavor_theme_ from "./routes/tags/flavor/theme/[flavor]/[theme].tsx";
import * as $terms from "./routes/terms.tsx";
import * as $words_word_ from "./routes/words/[word].tsx";
import * as $Bookshelf from "./islands/Bookshelf.tsx";
import * as $GtagEvent from "./islands/GtagEvent.tsx";
import * as $LazyLoadOGP from "./islands/LazyLoadOGP.tsx";
import * as $OnTranslatedEvent from "./islands/OnTranslatedEvent.tsx";
import * as $Printer from "./islands/Printer.tsx";
import * as $YoutubeAudio from "./islands/YoutubeAudio.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/ads.txt.ts": $ads_txt,
    "./routes/bookshelf.ts": $bookshelf,
    "./routes/index.tsx": $index,
    "./routes/lp/forCN.tsx": $lp_forCN,
    "./routes/lp/forES.tsx": $lp_forES,
    "./routes/lp/forJP.tsx": $lp_forJP,
    "./routes/lp/forPT.tsx": $lp_forPT,
    "./routes/lp/forTW.tsx": $lp_forTW,
    "./routes/pages/[date].tsx": $pages_date_,
    "./routes/report.tsx": $report,
    "./routes/robots.txt.ts": $robots_txt,
    "./routes/sitemap.xml.ts": $sitemap_xml,
    "./routes/tags/flavor/[flavor].tsx": $tags_flavor_flavor_,
    "./routes/tags/flavor/theme/[flavor]/[theme].tsx":
      $tags_flavor_theme_flavor_theme_,
    "./routes/terms.tsx": $terms,
    "./routes/words/[word].tsx": $words_word_,
  },
  islands: {
    "./islands/Bookshelf.tsx": $Bookshelf,
    "./islands/GtagEvent.tsx": $GtagEvent,
    "./islands/LazyLoadOGP.tsx": $LazyLoadOGP,
    "./islands/OnTranslatedEvent.tsx": $OnTranslatedEvent,
    "./islands/Printer.tsx": $Printer,
    "./islands/YoutubeAudio.tsx": $YoutubeAudio,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
