#!/bin/bash

ls static/img/bookshelf/archeology_x_academic-essay.jpg 1>/dev/null 2>&1 || echo archeology_x_academic-essay
ls static/img/bookshelf/archeology_x_gothic.jpg 1>/dev/null 2>&1 || echo archeology_x_gothic
ls static/img/bookshelf/archeology_x_mystery.jpg 1>/dev/null 2>&1 || echo archeology_x_mystery
ls static/img/bookshelf/archeology_x_romance.jpg 1>/dev/null 2>&1 || echo archeology_x_romance
ls static/img/bookshelf/archeology_x_sf.jpg 1>/dev/null 2>&1 || echo archeology_x_sf
ls static/img/bookshelf/architecture_x_academic-essay.jpg 1>/dev/null 2>&1 || echo architecture_x_academic-essay
ls static/img/bookshelf/architecture_x_fantasy.jpg 1>/dev/null 2>&1 || echo architecture_x_fantasy
ls static/img/bookshelf/architecture_x_sf.jpg 1>/dev/null 2>&1 || echo architecture_x_sf
ls static/img/bookshelf/architecture_x_steampunk.jpg 1>/dev/null 2>&1 || echo architecture_x_steampunk
ls static/img/bookshelf/art_x_academic-essay.jpg 1>/dev/null 2>&1 || echo art_x_academic-essay
ls static/img/bookshelf/art_x_gothic.jpg 1>/dev/null 2>&1 || echo art_x_gothic
ls static/img/bookshelf/art_x_romance.jpg 1>/dev/null 2>&1 || echo art_x_romance
ls static/img/bookshelf/art_x_steampunk.jpg 1>/dev/null 2>&1 || echo art_x_steampunk
ls static/img/bookshelf/culture_x_academic-essay.jpg 1>/dev/null 2>&1 || echo culture_x_academic-essay
ls static/img/bookshelf/culture_x_fantasy.jpg 1>/dev/null 2>&1 || echo culture_x_fantasy
ls static/img/bookshelf/culture_x_historical-fiction.jpg 1>/dev/null 2>&1 || echo culture_x_historical-fiction
ls static/img/bookshelf/dance_x_fantasy.jpg 1>/dev/null 2>&1 || echo dance_x_fantasy
ls static/img/bookshelf/dance_x_sf.jpg 1>/dev/null 2>&1 || echo dance_x_sf
ls static/img/bookshelf/design_x_academic-essay.jpg 1>/dev/null 2>&1 || echo design_x_academic-essay
ls static/img/bookshelf/design_x_magical-realism.jpg 1>/dev/null 2>&1 || echo design_x_magical-realism
ls static/img/bookshelf/economy_x_steampunk.jpg 1>/dev/null 2>&1 || echo economy_x_steampunk
ls static/img/bookshelf/economy_x_thriller.jpg 1>/dev/null 2>&1 || echo economy_x_thriller
ls static/img/bookshelf/education_x_young-adult.jpg 1>/dev/null 2>&1 || echo education_x_young-adult
ls static/img/bookshelf/engineering_x_sf.jpg 1>/dev/null 2>&1 || echo engineering_x_sf
ls static/img/bookshelf/ethics_x_academic-essay.jpg 1>/dev/null 2>&1 || echo ethics_x_academic-essay
ls static/img/bookshelf/ethics_x_crime.jpg 1>/dev/null 2>&1 || echo ethics_x_crime
ls static/img/bookshelf/fashion_x_cyberpunk.jpg 1>/dev/null 2>&1 || echo fashion_x_cyberpunk
ls static/img/bookshelf/fashion_x_historical-romance.jpg 1>/dev/null 2>&1 || echo fashion_x_historical-romance
ls static/img/bookshelf/fashion_x_romance.jpg 1>/dev/null 2>&1 || echo fashion_x_romance
ls static/img/bookshelf/fashion_x_steampunk.jpg 1>/dev/null 2>&1 || echo fashion_x_steampunk
ls static/img/bookshelf/film_x_gothic.jpg 1>/dev/null 2>&1 || echo film_x_gothic
ls static/img/bookshelf/film_x_horror.jpg 1>/dev/null 2>&1 || echo film_x_horror
ls static/img/bookshelf/film_x_post-apocalyptic.jpg 1>/dev/null 2>&1 || echo film_x_post-apocalyptic
ls static/img/bookshelf/mathematics_x_academic-essay.jpg 1>/dev/null 2>&1 || echo mathematics_x_academic-essay
ls static/img/bookshelf/mathematics_x_dystopian.jpg 1>/dev/null 2>&1 || echo mathematics_x_dystopian
ls static/img/bookshelf/mathematics_x_steampunk.jpg 1>/dev/null 2>&1 || echo mathematics_x_steampunk
ls static/img/bookshelf/music_x_cyberpunk.jpg 1>/dev/null 2>&1 || echo music_x_cyberpunk
ls static/img/bookshelf/music_x_horror.jpg 1>/dev/null 2>&1 || echo music_x_horror
ls static/img/bookshelf/music_x_romance.jpg 1>/dev/null 2>&1 || echo music_x_romance
ls static/img/bookshelf/philosophy_x_romance.jpg 1>/dev/null 2>&1 || echo philosophy_x_romance
ls static/img/bookshelf/philosophy_x_surrealism.jpg 1>/dev/null 2>&1 || echo philosophy_x_surrealism
ls static/img/bookshelf/photography_x_historical-romance.jpg 1>/dev/null 2>&1 || echo photography_x_historical-romance
ls static/img/bookshelf/photography_x_post-apocalyptic.jpg 1>/dev/null 2>&1 || echo photography_x_post-apocalyptic
ls static/img/bookshelf/photography_x_thriller.jpg 1>/dev/null 2>&1 || echo photography_x_thriller
ls static/img/bookshelf/politics_x_courtroom-drama.jpg 1>/dev/null 2>&1 || echo politics_x_courtroom-drama
ls static/img/bookshelf/politics_x_sf.jpg 1>/dev/null 2>&1 || echo politics_x_sf
ls static/img/bookshelf/politics_x_thriller.jpg 1>/dev/null 2>&1 || echo politics_x_thriller
ls static/img/bookshelf/science_x_gothic.jpg 1>/dev/null 2>&1 || echo science_x_gothic
ls static/img/bookshelf/science_x_horror.jpg 1>/dev/null 2>&1 || echo science_x_horror
ls static/img/bookshelf/science_x_steampunk.jpg 1>/dev/null 2>&1 || echo science_x_steampunk
ls static/img/bookshelf/science_x_thriller.jpg 1>/dev/null 2>&1 || echo science_x_thriller
ls static/img/bookshelf/society_x_courtroom-drama.jpg 1>/dev/null 2>&1 || echo society_x_courtroom-drama
ls static/img/bookshelf/society_x_mystery.jpg 1>/dev/null 2>&1 || echo society_x_mystery
ls static/img/bookshelf/technology_x_academic-essay.jpg 1>/dev/null 2>&1 || echo technology_x_academic-essay
ls static/img/bookshelf/technology_x_cyberpunk.jpg 1>/dev/null 2>&1 || echo technology_x_cyberpunk
ls static/img/bookshelf/technology_x_horror.jpg 1>/dev/null 2>&1 || echo technology_x_horror
ls static/img/bookshelf/technology_x_post-apocalyptic.jpg 1>/dev/null 2>&1 || echo technology_x_post-apocalyptic
ls static/img/bookshelf/theater_x_romance.jpg 1>/dev/null 2>&1 || echo theater_x_romance
ls static/img/bookshelf/theater_x_steampunk.jpg 1>/dev/null 2>&1 || echo theater_x_steampunk
ls static/img/bookshelf/theater_x_thriller.jpg 1>/dev/null 2>&1 || echo theater_x_thriller
