Level_1:
  Grammar:
    Topic: 'Basic Sentence Structure and Tenses & Continuous and Future Tenses'
    Overview: 'Understanding basic sentence structures and present/past tenses & Using continuous tenses and expressing the future'
    Detailed_Items:
      - 'Subject and verb'
      - 'Affirmative, negative, and interrogative sentences'
      - 'Present tense (habits, general facts)'
      - 'Past tense (events in the past)'
      - 'Present continuous tense'
      - 'Past continuous tense'
      - 'Future tense (will, be going to)'
  Vocabulary: 'Flesch-Kincaid: 0 to 3'
Level_2:
  Grammar:
    Topic: 'Modals and Perfect Tenses & Comparatives and Adjectives/Adverbs'
    Overview: 'Understanding modals and perfect tenses & Using comparative forms and modifiers'
    Detailed_Items:
      - 'Modals (can, must, should, may, etc.)'
      - 'Present perfect tense (experience, completion, continuation)'
      - 'Adjectives and adverbs'
      - 'Comparative and superlative forms'
      - 'Rules and expressions for comparison'
  Vocabulary: 'Flesch-Kincaid: down to 6'
Level_3:
  Grammar:
    Topic: 'Passive Voice and Relative Clauses & Conditionals and Participial Constructions'
    Overview: 'Using passive voice and relative clauses & Understanding conditionals and participial constructions'
    Detailed_Items:
      - 'Passive voice (be + past participle)'
      - 'Relative clauses (who, which, that)'
      - 'Conditionals (present, past)'
      - 'Participial constructions (using present and past participles)'
  Vocabulary: 'Flesch-Kincaid: down to 11'
Level_4:
  Grammar:
    Topic: 'Gerunds and Infinitives & Reported Speech and Question Tags'
    Overview: 'Understanding and using gerunds and infinitives & Using reported speech and question tags'
    Detailed_Items:
      - 'Gerunds (verb + ing)'
      - 'Infinitives (to + verb)'
      - 'Functions and usage differences'
      - 'Direct and indirect speech'
      - 'Reporting verbs'
      - 'Question tags (confirmation and emphasis)'
  Vocabulary: 'Flesch-Kincaid: down to 12'
Level_5:
  Grammar:
    Topic: 'Phrasal Verbs and Idioms & Articles and Quantifiers'
    Overview: 'Understanding and using phrasal verbs and idiomatic expressions & Correct usage of articles and quantifiers'
    Detailed_Items:
      - 'Common phrasal verbs'
      - 'Separable and inseparable phrasal verbs'
      - 'Everyday idioms and their meanings'
      - 'Definite and indefinite articles (the, a, an)'
      - 'Zero article'
      - 'Quantifiers (some, any, many, much, few, little)'
  Vocabulary: 'Flesch-Kincaid: down to 13'
Level_6:
  Grammar:
    Topic: 'Noun Clauses and Adjective Clauses & Conditionals Advanced'
    Overview: 'Using noun clauses and adjective clauses & Advanced usage of conditional sentences'
    Detailed_Items:
      - 'Noun clauses (that, if/whether)'
      - 'Adjective clauses (restrictive and non-restrictive)'
      - 'Zero conditional'
      - 'First conditional'
      - 'Second conditional'
      - 'Third conditional'
      - 'Mixed conditionals'
  Vocabulary: 'Flesch-Kincaid: down to 15'
Level_7:
  Grammar:
    Topic: 'Advanced Verb Tenses & Conjunctions and Transition Words'
    Overview: 'Mastering advanced verb tenses & Using conjunctions and transition words effectively'
    Detailed_Items:
      - 'Future perfect'
      - 'Future continuous'
      - 'Past perfect continuous'
      - 'Future perfect continuous'
      - 'Coordinating, subordinating, and correlative conjunctions'
      - 'Transition words for cohesion (e.g., however, therefore, moreover)'
  Vocabulary: 'Flesch-Kincaid: down to 17'
Level_8:
  Grammar:
    Topic: 'Advanced Sentence Structures & Review and Application'
    Overview: 'Mastering complex sentence structures & Reviewing and applying all grammar concepts'
    Detailed_Items:
      - 'Inversion in sentences'
      - 'Ellipsis and substitution'
      - 'Nominalization'
      - 'Comprehensive review of major topics'
      - 'Application through writing and speaking tasks'
      - 'Error analysis and correction'
  Vocabulary: 'Flesch-Kincaid: down to 18'
