import { QuizData } from "../../domains/quiz.ts";
const data: QuizData = {
  "event": {
    "event":
      "The first iPhone is announced by Steve Jobs, the co-founder and CEO of Apple.",
    "details":
      "On June 30th, 2007, Steve Jobs took to the stage at the Macworld conference in San Francisco and unveiled the iPhone, a revolutionary mobile phone that would change the face of technology forever. The iPhone was a multi-touch interface device that combined the functionality of an iPod, a mobile phone, and an internet communications device into one product.",
  },
  "date": "2025-06-30",
  "title": "The Shadow of the First iPhone",
  "body":
    "It was June 30th, 2007, and the world was about to change forever. Steve Jobs, the co-founder and CEO of Apple, stood on stage at the Macworld conference in San Francisco, ready to unveil the first iPhone. But little did anyone know that this revolutionary device would not only change the face of technology but also unleash a dark force that would haunt the world for centuries to come.  \n\n As soon as Steve Jobs revealed the iPhone's sleek design and multi-touch interface, the audience erupted in cheers and applause. But amidst the excitement, a strange feeling settled over the crowd. People began to feel an eerie presence, as if something was watching them from the shadows. At first, it was dismissed as mere paranoia, but soon, reports of strange occurrences started pouring in.  \n\n The iPhone's innovative technology had somehow awakened an ancient entity that had been dormant for centuries. This being, known only as 'The Glitch,' fed on the energy generated by the device's users. As people spent more time on their iPhones, they became increasingly disconnected from reality, and The Glitch grew stronger.  \n\n Now, the world was trapped in a never-ending cycle of addiction and terror. The first iPhone had unleashed a horror beyond comprehension, and humanity was powerless to stop it.",
  "word count": 213,
  "dialog": [
    {
      "Meg":
        "I'm still trying to wrap my head around The Glitch. I mean, an ancient entity that feeds on iPhone energy? That's crazy!",
    },
    {
      "Lui":
        "I've been teaching social studies for over 20 years, and I've never seen a novel tackle the intersection of technology and society like this one does.",
    },
    {
      "Billy":
        "I'm more concerned about the implications of The Glitch on our daily lives. I mean, if it's really growing stronger with every iPhone user...",
    },
    {
      "Kerry":
        "Dude, have you seen the sales numbers for iPhones? They're insane! And it's not just Apple making money; it's like a whole ecosystem around the device.",
    },
    {
      "Meg":
        "But what about the people who are being affected by The Glitch? Are they losing their grip on reality or something?",
    },
    {
      "Lui":
        "That's exactly what I'm worried about. If The Glitch continues to grow, we might see a complete breakdown of society as we know it.",
    },
    {
      "Billy":
        "I'm starting to think that the iPhone was never meant to be just a phone. It was always designed to change humanity in some way...",
    },
    {
      "Kerry":
        "Whoa, you're getting all philosophical on me, Billy! But seriously, what's next for humanity? Are we going to become completely dependent on technology?",
    },
    {
      "Meg":
        "I think the author is trying to say that our addiction to technology can have disastrous consequences. We need to find a balance between innovation and caution.",
    },
  ],
  "quiz": [
    {
      "question": "What was about to change forever on June 30th, 2007?",
      "options": [
        "The world's population",
        "The first iPhone's release",
        "The price of gasoline",
        "The weather forecast",
        "The stock market",
      ],
      "answer": 1,
    },
    {
      "question":
        "What strange feeling settled over the crowd when Steve Jobs revealed the iPhone's design and multi-touch interface?",
      "options": [
        "Excitement",
        "Fear",
        "Curiosity",
        "An eerie presence, as if something was watching them from the shadows",
        "Disgust",
      ],
      "answer": 3,
    },
    {
      "question": "What feeds on the energy generated by iPhone users?",
      "options": [
        "The Internet",
        "Social media",
        "The Glitch",
        "The stock market",
        "The weather forecast",
      ],
      "answer": 2,
    },
    {
      "question":
        "How does Billy feel about the implications of The Glitch on daily life?",
      "options": [
        "He's not concerned at all",
        "He's a bit worried, but not too much",
        "He's more concerned about the impact on society",
        "He thinks it's just a minor issue",
        "He's still trying to understand it",
      ],
      "answer": 2,
    },
    {
      "question":
        "What does Meg think is the author's message about technology and innovation?",
      "options": [
        "That we should use technology more often",
        "That we're addicted to technology, but that's okay",
        "That our addiction to technology can have disastrous consequences",
        "That we should just ignore The Glitch",
        "That it's all just a bunch of hype",
      ],
      "answer": 2,
    },
  ],
  "params": {
    "theme": "Technology",
    "flavor": "Horror",
    "models": {
      "main": "llama3.1",
      "novel": "llama3.1",
    },
    "level": "Level_3",
  },
};
export default data;
